import scrapy


class CompanymissionstatementItem(scrapy.Item):
    company = scrapy.Field()
    link = scrapy.Field()
    foundation = scrapy.Field()
    community_investment = scrapy.Field()
    community_focus = scrapy.Field()
    community_contribution = scrapy.Field()
    community_engagement = scrapy.Field()
    community_education = scrapy.Field()
    local_investment = scrapy.Field()
    local_focus = scrapy.Field()
    local_contribution = scrapy.Field()
    local_engagement = scrapy.Field()
    local_education = scrapy.Field()
    values_driven = scrapy.Field()
    mission_driven = scrapy.Field()
    funding_education_programs = scrapy.Field()
    community_development = scrapy.Field()
    financial_knowledge = scrapy.Field()
    tools_and_training_programs = scrapy.Field()
    focusing_on_financial_needs = scrapy.Field()
    financial_foundations = scrapy.Field()
    financial_programs = scrapy.Field()
    local_partnerships = scrapy.Field()
    promotion_of_volunteerism = scrapy.Field()
    underserved_communities = scrapy.Field()
    education_programs = scrapy.Field()
    community_programs = scrapy.Field()
    community_financial_programs = scrapy.Field()
    local_branch_programs = scrapy.Field()
    community_reinvestment = scrapy.Field()
    at_risk_populations = scrapy.Field()
    financial_literacy = scrapy.Field()
    employee_education = scrapy.Field()
    at_risk_youth = scrapy.Field()


class CompanyItem(scrapy.Item):
    company_name = scrapy.Field()
    company_link = scrapy.Field()